export const holidays = [
    {
        date: "1.01.2023",
        name: "novo leto",
        day: "nedelja",
        work_free_day: "da",
        day_num: 1,
        month_num: 1,
        year: 2023,
    },
    {
        date: "2.01.2023",
        name: "novo leto",
        day: "ponedeljek",
        work_free_day: "da",
        day_num: 2,
        month_num: 1,
        year: 2023,
    },
    {
        date: "8.02.2023",
        name: "Prešernov dan, slovenski kulturni praznik",
        day: "sreda",
        work_free_day: "da",
        day_num: 8,
        month_num: 2,
        year: 2023,
    },
    {
        date: "9.04.2023",
        name: "velika noč",
        day: "nedelja",
        work_free_day: "da",
        day_num: 9,
        month_num: 4,
        year: 2023,
    },
    {
        date: "10.04.2023",
        name: "velikonočni ponedeljek",
        day: "ponedeljek",
        work_free_day: "da",
        day_num: 10,
        month_num: 4,
        year: 2023,
    },
    {
        date: "27.04.2023",
        name: "dan boja proti okupatorju",
        day: "četrtek",
        work_free_day: "da",
        day_num: 27,
        month_num: 4,
        year: 2023,
    },
    {
        date: "1.05.2023",
        name: "praznik dela",
        day: "ponedeljek",
        work_free_day: "da",
        day_num: 1,
        month_num: 5,
        year: 2023,
    },
    {
        date: "2.05.2023",
        name: "praznik dela",
        day: "torek",
        work_free_day: "da",
        day_num: 2,
        month_num: 5,
        year: 2023,
    },
    {
        date: "28.05.2023",
        name: "binkoštna nedelja",
        day: "nedelja",
        work_free_day: "da",
        day_num: 28,
        month_num: 5,
        year: 2023,
    },
    {
        date: "8.06.2023",
        name: "dan Primoža Trubarja",
        day: "četrtek",
        work_free_day: "ne",
        day_num: 8,
        month_num: 6,
        year: 2023,
    },
    {
        date: "25.06.2023",
        name: "dan državnosti",
        day: "nedelja",
        work_free_day: "da",
        day_num: 25,
        month_num: 6,
        year: 2023,
    },
    {
        date: "15.08.2023",
        name: "Marijino vnebovzetje",
        day: "torek",
        work_free_day: "da",
        day_num: 15,
        month_num: 8,
        year: 2023,
    },
    {
        date: "17.08.2023",
        name: "združitev prekmurskih Slovencev z matičnim narodom",
        day: "četrtek",
        work_free_day: "ne",
        day_num: 17,
        month_num: 8,
        year: 2023,
    },
    {
        date: "15.09.2023",
        name: "vrnitev Primorske k matični domovini",
        day: "petek",
        work_free_day: "ne",
        day_num: 15,
        month_num: 9,
        year: 2023,
    },
    {
        date: "25.10.2023",
        name: "dan suverenosti",
        day: "sreda",
        work_free_day: "ne",
        day_num: 25,
        month_num: 10,
        year: 2023,
    },
    {
        date: "31.10.2023",
        name: "dan reformacije",
        day: "torek",
        work_free_day: "da",
        day_num: 31,
        month_num: 10,
        year: 2023,
    },
    {
        date: "1.11.2023",
        name: "dan spomina na mrtve",
        day: "sreda",
        work_free_day: "da",
        day_num: 1,
        month_num: 11,
        year: 2023,
    },
    {
        date: "23.11.2023",
        name: "dan Rudolfa Maistra",
        day: "četrtek",
        work_free_day: "ne",
        day_num: 23,
        month_num: 11,
        year: 2023,
    },
    {
        date: "25.12.2023",
        name: "božič",
        day: "ponedeljek",
        work_free_day: "da",
        day_num: 25,
        month_num: 12,
        year: 2023,
    },
    {
        date: "26.12.2023",
        name: "dan samostojnosti in enotnosti",
        day: "torek",
        work_free_day: "da",
        day_num: 26,
        month_num: 12,
        year: 2023,
    },
];
